<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyVersion>2025.6.15.87</AssemblyVersion>
    <FileVersion>2025.6.15.87</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Krafs.Rimworld.Ref" Version="1.5.4409" />
    <PackageReference Include="Lib.Harmony" Version="2.3.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\jl08lib\jl08lib.csproj" />
    <ProjectReference Include="..\LightsOut2.Core\LightsOut2.Core.csproj" />
  </ItemGroup>

</Project>
