<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyVersion>2025.11.2.34</AssemblyVersion>
    <FileVersion>2025.11.2.34</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Krafs.Rimworld.Ref" Version="1.5.4409" />
    <PackageReference Include="Lib.Harmony" Version="2.3.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\jl08lib\jl08lib.csproj" />
    <ProjectReference Include="..\LightsOut2.Core\LightsOut2.Core.csproj" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="call $(ProjectDir)..\..\..\post-build.cmd" />
  </Target>

</Project>
