<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyVersion>2025.6.15.55</AssemblyVersion>
    <FileVersion>2025.6.15.55</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="jl08lib.Tests" />
    <PackageReference Include="Krafs.Rimworld.Ref" Version="1.5.4409" />
    <PackageReference Include="Lib.Harmony" Version="2.3.6" />
  </ItemGroup>

</Project>
