<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net472</TargetFramework>
    <AssemblyVersion>2025.6.15.96</AssemblyVersion>
    <FileVersion>2025.6.15.96</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Krafs.Rimworld.Ref" Version="1.5.4409" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.9.2" />
    <PackageReference Include="MSTest.TestFramework" Version="3.9.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\jl08lib\jl08lib.csproj" />
  </ItemGroup>

</Project>
