<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyVersion>2025.7.5.8</AssemblyVersion>
    <FileVersion>2025.7.5.8</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\jl08lib\jl08lib.csproj" />
  </ItemGroup>

</Project>
